//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheoreticalClass
    {
        public int Id { get; set; }
        public System.DateTime Time { get; set; }
        public int RoomNo { get; set; }
        public string UserId { get; set; }
        public int UserId1 { get; set; }
        public int StaffId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
